source 'https://rubygems.org'

gem 'breakpoint'
gem 'coffee-script', '~> 2.3.0'
gem 'compass', '~> 1.0.0'
gem 'middleman', '~> 3.3.4'
gem 'middleman-emblem'
gem 'middleman-livereload', '~> 3.3.4'
gem 'middleman-slim'
gem 'sass', '~> 3.3.14'
gem 'sassy-buttons'
gem 'slim', '~> 2.0.3'
gem 'sprockets'
gem 'sprockets-handlebars_template', require: 'sprockets/ember_handlebars_template'
gem 'susy', '~> 2.1.1'
